### ISSUE TITLE
docs: document how to spin up this project

### ISSUE THREAD

**Issue by marcelovicentegc** [eutiveumsonho/amfa#5]
How to start developing this project? This should be documented under some section on README, just as in, for example: https://github.com/eutiveumsonho/chiron?tab=readme-ov-file#development

### Tips
- This project uses [Deno](https://deno.com/), meaning that developers must have Deno installed along with its code editor plugin. 
- To run the project, you need to execute the `start.sh` file: 
```sh
sh start.sh
```

**Comment by radilua** [comment]
Issue solved by https://github.com/eutiveumsonho/amfa/commit/5e98bfa5cffc28aeebb72ca24a67b6a4c91e0a3c
